const $ = id => document.getElementById(id);
let controlMessage='', controlUntil=0, selectedRun='', snapshot, selectedArtifact, lastGood = 0, lastEvents = '', lastAssets = '', busy = false;
const names = { 'opportunity-brief.md':'Launch brief', 'outreach-draft.md':'Introduction draft', 'proof-kit.json':'Your proof kit', 'docker-validation.json':'Checked in Docker', 'linkedin-post.md':'LinkedIn draft', 'x-thread.md':'X thread' };
const toolLabel = tool => /recall|memory|cognee/.test(tool) ? 'memory' : /research|bright|source|scrape|public_target/.test(tool) ? 'research' : /asset|proof/.test(tool) ? 'proof' : /save|write|artifact/.test(tool) ? 'writing' : /docker|valid/.test(tool) ? 'checking' : 'thinking';
const actionCopy = {
  ready:['Watching your inbox','Ready for the next work event.','Give me a piece of finished work. I’ll build its launch pack while you keep going.'],
  thinking:['Working','Choosing the next useful move.','Your goals and evidence guide what I do next.'],
  memory:['Remembering · Cognee','Connecting what I know about you.','Your goals, working preferences and existing projects are coming into context.'],
  research:['Researching · Bright Data','Putting your work in context.','Research Synth is reading live sources before choosing the angle for your launch.'],
  proof:['Choosing your proof','You’ve already built the evidence.','Finding the existing project or demo that makes the strongest case.'],
  writing:['Making your deliverable','Your next launch is taking shape.','Writing your LinkedIn post, X thread and introduction from actual evidence.'],
  checking:['Checking · Docker','Making sure the work holds together.','An offline container is checking the files, citations and proof kit structure.'],
  completed:['Ready for George','Your launch pack is ready.','The team finished your posts, proof kit and introduction. Open the work below.'],
  error:['Needs attention','The task hit a real obstacle.','The work and evidence are saved below. See the latest activity before retrying.'],
  interrupted:['Paused','The connection to this run ended.','The saved activity and any completed files are still available below.'],
  disconnected:['Connection lost','Waiting for the live connection.','The avatar will continue when the Mac responds again.']
};
function displayAction(action, detail) { document.body.dataset.action=action; const copy=actionCopy[action]||actionCopy.thinking; $('action-badge').textContent=copy[0]; $('action-title').textContent=copy[1]; $('action-detail').textContent=detail||copy[2]; }
function detailText(e) { const d=e.detail; if(typeof d==='string') return d; if(d&&typeof d==='object') return d.message||d.summary||d.status||''; return ''; }
function eventLabel(e) {
  if(e.event==='synth_started')return (e.parent||'Digital George')+' → '+(e.actor||'Synth')+' · work handed over';
  if(e.event==='synth_completed')return (e.actor||'Synth')+' → '+(e.parent||'Digital George')+(detailText(e)==='error'?' · handoff failed':' · findings returned');
  const action=toolLabel(e.tool||'');
  const verbs={memory:'Read your memory',research:'Read live launch context',proof:'Selected your existing proof',writing:'Saved the deliverable',checking:'Checked files in Docker',thinking:e.tool||'Reasoned about the next action'};
  if(e.event==='tool_started') return ({memory:'Recalling your memory',research:'Reading live launch context',proof:'Inspecting your existing proof',writing:'Writing the deliverable',checking:'Checking files in Docker',thinking:'Working on the next action'})[action];
  if(e.event==='tool_completed'&&detailText(e)==='retrieved_error_page')return 'Source returned an error page · preserved as evidence';
  if(e.event==='tool_completed') return verbs[action] + (detailText(e)==='error'?' · reported an error':'');
  return detailText(e)||({started:'Started your task',completed:'The task is ready for review',error:'The task needs attention'}[e.event])||e.event;
}
function panel(name) { document.querySelectorAll('.evidence-panel').forEach(el=>el.hidden=el.id!==name); document.querySelectorAll('[data-panel]').forEach(el=>{el.classList.toggle('selected',el.dataset.panel===name);el.setAttribute('aria-expanded',String(el.dataset.panel===name));}); if(name==='memory') loadGraph(); }
document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>panel(button.dataset.panel)));
function showArtifact(name) { selectedArtifact=name; const file=snapshot?.artifacts.find(a=>a.name===name); if(!file)return; $('artifact-content').textContent=file.text; const a=$('artifact-download');a.hidden=false;a.href='/api/artifact/'+encodeURIComponent(name)+(selectedRun?'?run='+encodeURIComponent(selectedRun):'');a.target='_blank';a.rel='noreferrer';document.querySelectorAll('[data-artifact]').forEach(b=>b.classList.toggle('selected',b.dataset.artifact===name)); }
function render(s) {
  snapshot=s;lastGood=Date.now();$('connection').textContent=selectedRun?'Saved run':s.status==='running'?'Working live':'Connected to Mac';$('connection-dot').className='online';document.body.dataset.running=String(s.status==='running');
  const last=s.events.at(-1); const actor=s.status==='running'?(last?.event==='synth_completed'?(last.parent||'Digital George'):(last?.actor||'Digital George')):'Digital George';document.body.dataset.actor=actor;document.querySelectorAll('[data-actor]').forEach(el=>el.classList.toggle('active',el.dataset.actor===actor&&s.status==='running'));$('trail-action').textContent=s.status==='running'?actor:s.status==='completed'?'Finished work':'Always-on launch concierge';for(const [name,id]of [['Research Synth','research-status'],['Proof Synth','proof-status']]){const seen=[...s.events].reverse().find(e=>e.actor===name);$(id).textContent=!seen?(name==='Research Synth'?'Ready to investigate':'Ready to choose your work'):seen.event==='synth_completed'?'Findings returned':s.status==='running'?'Working on your task':s.status==='error'?'Run stopped':'Completed';}if(last?.event==='synth_started')$('handoff-note').textContent=(last.parent||'Digital George')+' handed work to '+last.actor;if(last?.event==='synth_completed')$('handoff-note').textContent=last.actor+' returned findings to '+(last.parent||'Digital George');const source=[...s.events].reverse().find(e=>e.detail?.url);if(source)$('source-live').textContent=new URL(source.detail.url).hostname+' · '+(source.detail.status==='retrieved_error_page'?'source unavailable':source.detail.status==='retrieved'?'read live':source.detail.status||'read');const action=s.status==='running'?(last?.event==='tool_started'?toolLabel(last.tool||''):last?.event==='synth_started'?(actor==='Proof Synth'?'proof':actor==='Research Synth'?'research':'thinking'):'thinking'):s.status;displayAction(action,s.status==='error'||(s.status==='completed'&&s.runState?.phase==='correction')?detailText(last):undefined);if(s.status==='completed'&&s.runState?.phase==='correction'){$('action-title').textContent='I’ll remember that.';}
  if(s.daemon){$('daemon-status').textContent=s.daemon.status==='preview'?'Local preview':s.daemon.status==='error'?'Daemon needs attention':s.daemon.status==='working'?'Daemon working':'Daemon watching';} $('updated').textContent=(selectedRun?'Saved run · ':'Live · ')+new Date(s.checkedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});$('start').disabled=s.workerBusy||!s.canRun||busy;
  $('control-note').textContent=Date.now()<controlUntil?controlMessage:!s.canRun?'Presentation preview. Live execution runs on your MacBook Pro.':s.status==='running'?'Working on your MacBook Pro. You can inspect every action below.':'Uses your Codex subscription. External messages remain drafts.';
  $('event-count').textContent=String(s.events.length);$('result-count').textContent=String(s.artifacts.length);$('memory-count').textContent=s.graph.nodes?String(s.graph.nodes):'—';
  const decisions=s.decisions||[];$('decision-count').textContent=String(decisions.length);const decisionKey=JSON.stringify(decisions);if($('decision-list').dataset.key!==decisionKey){$('decision-list').dataset.key=decisionKey;$('decision-list').replaceChildren();if(!decisions.length)$('decision-list').textContent='This run has no Jev decision receipts. New tasks record them as the team works.';for(const d of [...decisions].sort((a,b)=>String(b.at||'').localeCompare(String(a.at||'')))){const row=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('pre');const chosen=typeof d.hostSelectedAction==='string'?d.hostSelectedAction:JSON.stringify(d.hostSelectedAction||'No host action recorded');summary.textContent=chosen+' · '+(d.disposition||'unavailable');body.textContent=JSON.stringify({reason:d.reason,recommendation:d.recommendation,hostAction:d.hostSelectedAction,mode:d.mode,label:d.label,genuineJevModelInference:d.genuineJevModelInference},null,2);row.append(summary,body);$('decision-list').append(row);}}
  const eventKey=JSON.stringify(s.events);if(eventKey!==lastEvents){lastEvents=eventKey;$('timeline').replaceChildren();if(!s.events.length){const li=document.createElement('li');li.className='empty';li.textContent='Your next task will appear here, one real action at a time.';$('timeline').append(li);}for(const e of [...s.events].reverse().slice(0,20)){const li=document.createElement('li'),label=document.createElement('span'),time=document.createElement('time');label.textContent=(e.actor&&e.event!=='synth_started'&&e.event!=='synth_completed'?e.actor+' · ':'')+eventLabel(e);time.textContent=new Date(e.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});li.append(label,time);$('timeline').append(li);}}
  const keys=s.artifacts.map(a=>a.name).join('|');if($('artifact-tabs').dataset.keys!==keys){$('artifact-tabs').dataset.keys=keys;$('artifact-tabs').replaceChildren();$('result-strip').replaceChildren();$('result-strip').hidden=!s.artifacts.length;for(const a of s.artifacts){const b=document.createElement('button');b.textContent=names[a.name]||a.name;b.dataset.artifact=a.name;b.addEventListener('click',()=>showArtifact(a.name));$('artifact-tabs').append(b);const quick=b.cloneNode(true);quick.addEventListener('click',()=>{panel('results');showArtifact(a.name);$('results').scrollIntoView({behavior:'smooth',block:'nearest'});});$('result-strip').append(quick);}}
  if(s.artifacts.length)showArtifact(selectedArtifact&&s.artifacts.some(a=>a.name===selectedArtifact)?selectedArtifact:s.artifacts[0].name);
  if(!lastAssets){lastAssets='loaded';for(const a of s.assets){const article=document.createElement('article'),video=document.createElement('video'),h=document.createElement('h3'),p=document.createElement('p'),link=document.createElement('a');video.controls=true;video.preload='none';video.src=a.video;video.poster=a.poster;video.setAttribute('aria-label',a.name+' existing recording');h.textContent=a.name;p.textContent=a.description;link.href=a.source;link.target='_blank';link.rel='noreferrer';link.textContent='See the source ↗';article.append(h,p,link);$('asset-list').append(article);}}
}
async function poll(){try{const response=await fetch('/api/state'+(selectedRun?'?run='+encodeURIComponent(selectedRun):''),{signal:AbortSignal.timeout(4000)});if(!response.ok)throw Error();render(await response.json());}catch{if(Date.now()-lastGood>5000){document.body.dataset.running='false';$('connection').textContent='Disconnected';$('connection-dot').className='';displayAction('disconnected');}}finally{setTimeout(poll,1000);}}
async function loadGraph(){try{const res=await fetch('/api/graph',{signal:AbortSignal.timeout(18000)});const g=await res.json();const all=Array.isArray(g.nodes)?g.nodes:[];const links=g.links||g.edges||[];drawUniverse(all,links);$('universe-memory').textContent=g.status==='live'?all.length+' connected nodes · live graph':'Memory graph unavailable';$('memory-count').textContent=String(all.length);$('graph-note').textContent=g.status==='live'?`${all.length} nodes · ${links.length} relationships in this live sample · Cognee digital_george`:g.error||'Graph unavailable';
  const nodes=all.filter(n=>!['DocumentChunk','TextDocument','Document'].includes(n.type)&&String(n.name||'').length<100).slice(0,34);const map=new Map(nodes.map((n,i)=>{const a=i*2.399963;const radius=35+Math.sqrt(i/Math.max(nodes.length,1))*145;return[String(n.id),{...n,x:400+Math.cos(a)*radius*1.8,y:200+Math.sin(a)*radius}];}));const svg=$('graph');svg.replaceChildren();const ns='http://www.w3.org/2000/svg';for(const l of links){const a=map.get(String(l.source?.id||l.source)),b=map.get(String(l.target?.id||l.target));if(!a||!b)continue;const line=document.createElementNS(ns,'line');for(const[k,v]of Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y}))line.setAttribute(k,String(v));svg.append(line);}for(const n of map.values()){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',n.x);circle.setAttribute('cy',n.y);circle.setAttribute('r',String(Math.min(9,4+Number(n.degree||1)/8)));circle.setAttribute('tabindex','0');circle.setAttribute('role','button');circle.setAttribute('aria-label',String(n.name||n.type||'Memory'));const select=()=>{$('node-detail').textContent=String(n.name||'Memory')+'\n\n'+String(n.text||n.type||'')+'\n\nSource: '+String(n.document_id||n.provenance||n.id);};circle.addEventListener('click',select);circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}});const label=document.createElementNS(ns,'text');label.setAttribute('x',n.x+10);label.setAttribute('y',n.y+3);label.textContent=String(n.name||n.type||'').slice(0,27);svg.append(circle,label);}}
catch{$('graph-note').textContent='Cognee is taking longer to respond. Open Memory again to retry.';}}
$('start').addEventListener('click',async()=>{busy=true;$('start').disabled=true;try{const response=await fetch('/api/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:$('goal').value,phase:$('phase').value})});const result=await response.json();if(!response.ok)throw Error(result.error);if(result.existingRun){selectedRun=result.existingRun;loadRuns();panel('results');controlMessage='This task already has a saved run. Showing its actual work.';}else{selectedRun='';$('run-select').value='';panel('activity');controlMessage='Task queued in your work inbox.';}controlUntil=Date.now()+10000;}catch(e){controlMessage=e.message;controlUntil=Date.now()+15000;$('control-note').textContent=e.message;}finally{busy=false;}});
$('phase').addEventListener('change',()=>{if($('phase').value==='correction')$('goal').value='Remember my preference: use my own writing and existing demos, videos and GitHub projects. Digital George should reduce the work I have to do. Distinguish facts about me from guesses, and prepare useful finished work.';if($('phase').value==='fresh')$('goal').value='Start fresh. Recall my actual public X writing examples and my preferences from Cognee. Prepare a new launch pack from my existing shipped work, using the voice supported by those examples. Explain which sourced memory changed the result.';});
$('present').addEventListener('click',()=>{const on=document.body.classList.toggle('presenting');$('present').textContent=on?'Exit presentation':'Present ↗';window.scrollTo({top:0,behavior:'smooth'});});
async function loadRuns(){try{const r=await fetch('/api/runs');if(!r.ok)return;const data=await r.json();const select=$('run-select');const value=selectedRun;select.replaceChildren(new Option('Live task',''));for(const run of data.runs){select.add(new Option(run.id.slice(0,19).replace('T',' · ')+' · '+run.phase,run.id));}select.value=value;}catch{}}
$('run-select').addEventListener('change',()=>{selectedRun=$('run-select').value;selectedArtifact=undefined;lastEvents='';$('artifact-tabs').dataset.keys='';$('artifact-content').textContent='Loading saved work…';$('artifact-download').hidden=true;});
loadRuns();setInterval(loadRuns,15000);
poll();
loadGraph();

function drawUniverse(nodes,links){const svg=$('neural-field');if(!svg)return;svg.replaceChildren();const ns='http://www.w3.org/2000/svg';const visible=nodes.filter(n=>String(n.name||'').length<65&&!['DocumentChunk','TextDocument','Document'].includes(n.type)).slice(0,45);const map=new Map(visible.map((n,i)=>{const angle=i*2.399963;const r=120+Math.sqrt(i/visible.length)*240;return[String(n.id),{...n,x:500+Math.cos(angle)*r*1.2,y:250+Math.sin(angle)*r*.57}];}));for(const l of links){const a=map.get(String(l.source?.id||l.source)),b=map.get(String(l.target?.id||l.target));if(!a||!b)continue;const line=document.createElementNS(ns,'line');for(const[k,v]of Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y}))line.setAttribute(k,v);svg.append(line);}for(const n of map.values()){const c=document.createElementNS(ns,'circle');c.setAttribute('cx',n.x);c.setAttribute('cy',n.y);c.setAttribute('r',String(Math.min(3,1+Number(n.degree||1)/15)));svg.append(c);if(n.x<340||n.x>660){const label=document.createElementNS(ns,'text');label.setAttribute('x',n.x+6);label.setAttribute('y',n.y+2);label.textContent=String(n.name||'').slice(0,22);svg.append(label);}}}

function renderPersona(){const p=window.digitalGeorgeProfile;if(!p)return;const host=$('persona-profile');const identity=document.createElement('div'),name=document.createElement('h3'),mission=document.createElement('p'),prefs=document.createElement('ul');name.textContent=p.name;mission.textContent='A profile built from your selected sources. '+p.mission;for(const i of [0,2,3]){const li=document.createElement('li');li.textContent=p.workingPreferences[i].text;li.title=p.workingPreferences[i].source;prefs.append(li);}identity.append(name,mission,prefs);const writing=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Selected public writing examples';writing.append(summary);for(const item of p.writingEvidence){const quote=document.createElement('blockquote'),text=document.createElement('p'),link=document.createElement('a');text.textContent=item.excerpt;link.textContent=new Date(item.date).toLocaleDateString()+' · Original post ↗';link.href=item.url;link.target='_blank';link.rel='noreferrer';quote.append(text,link);writing.append(quote);}const connections=document.createElement('details'),cs=document.createElement('summary');cs.textContent='Connected accounts and current limits';connections.append(cs);for(const item of p.connections){const row=document.createElement('p');row.textContent=item.service+' · '+item.status;connections.append(row);}host.append(identity,writing,connections);}
renderPersona();
